### ISSUE TITLE
Using Table from other software

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/TMT-Integrator#1]
Hi,
is it possible to use .tsv data generated by other software as input? can I tweak the headers/data for that?

Thanks!
D.

**Comment by huiyinc** [comment]
Hi,

I think it is possible to use tsv tables from different software tools, as long as the headers and content are consistent with those from Philosopher.
Please feel free to ask if you encounter any difficulty when doing it.
Thanks.

Huiyin

從我的iPhone傳送
