### ISSUE TITLE
Some empty column names in output

### ISSUE THREAD

**Issue by andreabc** [Nesvilab/TMT-Integrator#17]
Hi, thanks for the great tool! I successfully ran the philosopher pipeline (including TMT integrator) on my dataset, however, 3 column names are missing 
![image](https://user-images.githubusercontent.com/13284937/120566161-84dc4800-c3c3-11eb-85d4-e26c106bb2ea.png)

I checked and all sample IDs from my annotation files are present (except the pooled reference IDs), not sure what the extra columns correspond to. Any ideas?

Thanks for your help

**Comment by huiyinc** [comment]
Hi,

To figure out the issue, can you share your psm, fasta and TMT-Integrator parameter files with me?
Thanks.

Huiyin

**Comment by andreabc** [comment]
Ah I figured it out, I had some duplicate 'pooled' labels in 3 annotation files, when I rename the extra pooled channels there are no more issues. Thank you!

**Comment by anesvi** [comment]
This is actually a common problem… Hui-yin, should we check that the table has only one sample matching the reference tag?
And if more than one, give an error?

**Comment by huiyinc** [comment]
Hi Alexey,

I have added it in TMT-Integrator. So it will be in our next release. Thanks!

Huiyin
