### ISSUE TITLE
Can't edit two annotation files

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/TMT-Integrator#18]
I am trying to process a dataset with 2 x TMT11 sets, each with two pools. When I set up the experiment in FragPipe, there are two sets (Set1 and Set2) that have assigned annotation.txt files. However, the software won't let me select two different annotation files (either in different directories or with different names). Editing Set1, changes both Set1 and 2 annotation. What is the correct way to do this? Thanks, Matt

**Comment by sarah-haynes** [comment]
Hi Matt, are Set1 and Set2 in separate folders? FragPipe should allow you to edit multiple annotation.txt files if they are each in a different folder corresponding to the appropriate set/plex. This [tutorial](https://fragpipe.nesvilab.org/docs/tutorial_tmt-2plexes.html#load-the-data) has an example similar to yours.

Sarah

**Comment by mwfoster** [comment]
Sorry I missed that detail about the two separate folders. Thanks, Matt
