### ISSUE TITLE
Possible to exclude empty TMT channels from all normalisation steps?

### ISSUE THREAD

**Issue by p-bell** [Nesvilab/TMT-Integrator#27]
Hi,

I'm mining some TMT datasets from PRIDE, and I'm interested in peptide level quantification. 

In several of the datasets, the researchers used 16-plex TMT but didn't use all channels. As a result, the intensities for the 'empty' channels are much lower than for the other channels. My concern is that this would interfere with normalisation steps in TMT integrator. 

1) Is this a valid concern?
2) Please can you advise whether it is possible to exclude specific channels from TMT-Integrator?

Using 'abundance_peptide_None.tsv' isn't suitable, since I would still like to perform normalisation based on the TMT channels that have been used.

Thanks and best wishes,
Pete

**Comment by anesvi** [comment]
Hi Pete,
Yes, empty channels should be annotated as NA in annotation.txt files. That way they will be excluded from the TMT-Integrator output tables and from any normalization 
Best
Alexey

**Comment by p-bell** [comment]
Thanks a lot Alexey! That's great.

All the best,
Pete
