### ISSUE TITLE
TMT Quantification Question

### ISSUE THREAD

**Issue by barny116** [Nesvilab/TMT-Integrator#28]
Hi, 
I am new to using MSFragger, but I am really excited about its capabilities. 
I typically use PD to search my TMTPro 16-plex labeled peptide samples. However, I am trying a new application that PD is not suited for. 
Can you provide me with more information on the "min intensity (percent)" option? In my PD searches with TMT labels, I usually require a reporter ion S/N ratio of 10/1. 
Thanks,
Lea

**Comment by anesvi** [comment]
It is similar to the PD SN filter option. We remove PSMs with the intensity values falling in the lowest 5% (2.5% for PTM data). You can change these values, but what we set as defaults is what worked well for us in our tests.

**Comment by barny116** [comment]
Thank you so much for your prompt response.
Also, is there anyway to add correction values for the individual TMT
labels in MSFragger?
Typically, I set the co-isolation threshold to 25% in PD. I believe that
would be 75% in MSFragger's "min purity" option, as it is flipped? Is that
correct?
Thanks,
Lea

**Comment by anesvi** [comment]
We do not have the correction option. As far as Purity, yes it is flipped (so PD's 75% filter is Purity 25%. We recommend 50%, our default)

**Comment by barny116** [comment]
Awesome, thanks. Can you give me some insight on why your team chose not to include the correction step? 
-Lea

**Comment by anesvi** [comment]
We extensively tested it as part of CPTAC consortium benchmarking, and it was not helping and even creating occasional problems. We disabled that option a while back. At any rate, we do not plan to add it back any time soon as we have other priorities.
