### ISSUE TITLE
Consistent error- TMT integrator can't find the 'Purity' column

### ISSUE THREAD

**Issue by barny116** [Nesvilab/TMT-Integrator#30]
Hi, 
I am continuously obtaining an error about the TMT integrator not being able to find the 'Purity' column. 
I checked the psm.tsv and the column does not exist. 
Do you have any suggestions about how to solve this issue? 
Thanks

**Comment by anesvi** [comment]
Please send us the log file. But this usually happens when something not right with mzM files (e.g. an old version of msconvert was used, or the data from a new mass spec like Thermo Ascend generated in a way that is not supported by msconvert)
