### ISSUE TITLE
Empty TMT-Integrator Output

### ISSUE THREAD

**Issue by helloworld1631** [Nesvilab/TMT-Integrator#31]
Hello,

I meet a problem when running TMT-Integrator in FragPipe. It sucessfully finished but generated empty .tsv files (only headers).
I check the previous issue - Blank output files when running with Philosopher pipeline #7 ; empty TMT reports #10 ; Empty TMT Integrator outputs #16 . But I guess my problem is not due to Column headers/TMT annotations/FreeQuant.

In my psm.tsv files, there are TMT intensities but Purity column is 0. Could this be possible reason?
Thanks!

Here are thelog files of TMTIntegrator:

> TMT-Integrator v4.0.5
> Warning: All MS1 Intensities in C:\Users\zwang3136\Desktop\MSfragger_TMT_intergrater_only\psm.tsv are 0. TMT-Integrator will use summed MS2 reporter ion intensity instead of MS1 ion intensity as reference intensity for abundance calculation.
> Load parameters and check PSMs--- 0.01265 min.
> Load fasta--- 0.48938 min.
> UpdateColumns--- 0.03127 min.
> LoadPsms--- 0.00315 min.
> Take log and normalize--- 0.00000 min.
> PSM normalization--- 0.00000 min.
> outlierRemoval--- 0.00000 min.
> Collapse--- 0.00000 min.
> protNorm--- 0.00000 min.
> Report--- 0.00052 min.
> Total run time--- 0.53733 min.
> Finish!!!
> Process 'TmtIntegrator' finished, exit code: 0

**Comment by anesvi** [comment]
Yes something wrong with your mzML files -philosopher could not calculate Purity. Please use the latest version of msconvert. If the problem persists, then it means you have done unusual instrument settings. At any rate, not something we can easily fix. But I think you can change the Purity threshold to 0 and basically use all PSMs

**Comment by helloworld1631** [comment]
Thank you! Now I use mzML files generated by newest version of MSconvert and now it works.
