### ISSUE TITLE
Help!there is no Ref_int_pool colunm in abundance_MD.tsv in new version

### ISSUE THREAD

**Issue by xyzcc2007** [Nesvilab/TMT-Integrator#32]
Here is the old tsv
![960846850ae8f9c2a850874f0396993](https://github.com/Nesvilab/TMT-Integrator/assets/145945874/767d77b6-977f-445f-a82f-8be0be6e09ce)
![2b184315a56f1764c55eb0fff626fdf](https://github.com/Nesvilab/TMT-Integrator/assets/145945874/7493a78d-243b-4152-8a2d-b1cdb64169d6)
Here is the new version,we can see there is no pool.only single batch will get the pool column,but it is useless
![image](https://github.com/Nesvilab/TMT-Integrator/assets/145945874/fb9ea359-7268-4bb5-ae1b-a1458ba2c896)

**Comment by anesvi** [comment]
Sorry I cannot follow. If you use reference approach, there is no pool ( reference) left in the final tables. Read tutorials.

**Comment by xyzcc2007** [comment]
but the old version get the pool intensity

发自我的 iPhone

**Comment by anesvi** [comment]
We need to have access to your FragPipe results folder. Can you zip and share with us using e.g. Dropbox?

**Comment by xyzcc2007** [comment]
Sorry，We delete all the temp files，only keep the Tmt-report folder，could it be useful？

**Comment by anesvi** [comment]
No, we need to see your whole folder. You can replicate your problem on a small dataset and contact us again

**Comment by xyzcc2007** [comment]
Nowadays we couldn’t repeat the result，only get the no-pool one again and again.The only one confirmed is the old version is fragpipe 18，we used in Jan.23

发自我的 iPhone
