### ISSUE TITLE
Request for Assistance - TMT Integrator Issue in Quantification Step

### ISSUE THREAD

**Issue by lfu46** [Nesvilab/TMT-Integrator#33]
Dear Developers,

I am reaching out to bring to your attention an issue I have encountered with the TMT Integrator during my recent experiments. Unfortunately, I have been unable to generate TMT report files successfully, obtaining only files suffixed with "_None" that are empty.

In the course of my experiment, I utilized a single TMT-6 plex, categorizing them as one experiment group. Within the Quant (Isobaric) module, I opted for the "Virtual" option under Define reference and selected "All" for Group by. Notably, I did not employ any normalization method, setting it as "None." All other parameters were left at their default values.

Despite multiple attempts, the TMT Integrator has not yielded any reports. Interestingly, I observed abundance columns for each channel in the PSM.tsv file within my results. A warning message caught my attention: "_**All MS1 Intensities in E:\Macrophage_LPS_Treatment\Data\E_LF_Nuc_11052023\E_LF_Nuc_11052023\psm.tsv are 0. TMT-Integrator will use summed MS2 reporter ion intensity instead of MS1 ion intensity as a reference intensity for abundance calculation.**_" I am uncertain about the necessary actions in response to this warning.

Additionally, I noted a warning message from FreeQuant stating, "_**could not calculate the precursor purity score.**_" This has led me to consider potential issues with FreeQuant and Quant (Isobaric), as it appears that TMT Integrator serves as the final step in summarizing the results of the quantification process. However, I am unsure of the appropriate steps to take in light of these warning messages.

To facilitate your understanding, I have attached several screenshots and the log file from my search. It is worth mentioning that all other aspects of the search proceeded smoothly, except for the quantification step.

I would greatly appreciate your guidance and assistance in resolving this issue. Please let me know if you require any additional information to provide further insight into the problem.

Thank you for your time and support.

Best regards,
Longping

![abundance column from psm file](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/61efb319-024b-4e5b-875c-e2f9eb4327ec)
![Quant Module Configuration](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/cdd9c750-3dfd-4f4b-9acc-d02406b3e3f8)
![tmt-report result](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/88e2d5bf-4770-444f-b976-74a500bfc317)
[log_2023-11-23_16-01-38.txt](https://github.com/Nesvilab/TMT-Integrator/files/13593100/log_2023-11-23_16-01-38.txt)

**Comment by anesvi** [comment]
Please try reconverting from raw to mzML using the latest msconvert. Something was wrong with your files, perhaps you used an old version of tbd converter. If still the same problem, contact us again

**Comment by lfu46** [comment]
Dear Alexey,

Thank you for your prompt response and valuable suggestion; it was incredibly helpful. I successfully used msconvert to convert my raw files to mzML files, and the TMT report was generated without any issues on protein and gene level.

However, I have encountered a new challenge while attempting to run TMT quantification on a single PTM site or multiple PTM sites. Specifically, I am aiming to quantify the modification **_STC(528.2859)_**. This modification was designated as a variable modification in the MSFragger searching parameters. Additionally, I employed ptmprophet for PTM localization on this modification.

Despite these preparations, I am facing difficulties when opting for site-level quantification in the Quant (Isobaric) module—whether for a single or multiple sites. Setting the Mod tag as **_S(528.2859), T(528.2859), C(528.2859)_** does not yield successful results. Instead, I only obtain blank files with column names.

To provide a clearer understanding of the issue, I have attached several screenshots and the log file from my searching process.

I would greatly appreciate it if you could offer some insights or suggestions on how to overcome this problem. Your assistance is invaluable to me.

Thank you very much for your time and help.

Best regards,
Longping
![quant configuration](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/31852c3f-b25b-4b53-a1a8-388c7c928050)
![result files](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/9b814ad3-c2d7-42b8-9bc2-d3d76e44844d)
[log_2023-12-07_15-05-25.txt](https://github.com/Nesvilab/TMT-Integrator/files/13604734/log_2023-12-07_15-05-25.txt)

**Comment by anesvi** [comment]
I don't see anywhere in your log file that you are running PTMProphet. Please TMT phospho workflow as example

**Comment by lfu46** [comment]
Thank you for your prompt response.

I regret to inform you that I made a mistake in my previous submission. Unfortunately, I only uploaded the log containing the Quant (Isobaric) part. I apologize for any inconvenience this may have caused.

Kindly find attached the corrected log, which now includes both the Validation and Quant (Isobaric) parts. If you require any additional information, please feel free to reach out without hesitation. Your assistance is greatly appreciated.

Thank you for your understanding, and I look forward to your feedback.
[log_2023-12-07_15-43-37.txt](https://github.com/Nesvilab/TMT-Integrator/files/13605115/log_2023-12-07_15-43-37.txt)

**Comment by anesvi** [comment]
I think the issue is you have fixed mod on C and variable on top of it. Please remove C*57 from the search. Maybe add C+57 as variable

**Comment by lfu46** [comment]
Actually, I have already designated **_C(57.02146)_** as a variable modification in accordance with my experimental design. I apologize for any lack of clarity. I have attached my workflow file, and you should be able to review all of my settings therein.
[Metabolic_Labeling_C57_variable_1.txt](https://github.com/Nesvilab/TMT-Integrator/files/13605275/Metabolic_Labeling_C57_variable_1.txt)

**Comment by anesvi** [comment]
Then I don't know. Need to have your data to run it myself

**Comment by lfu46** [comment]
Thank you for your prompt response. I have compressed all my mzML files along with my workflow, and included several screenshots for reference. I've shared them with you via Google Drive. You can access the files through this link.
https://drive.google.com/file/d/1ouQ5ksBrY9JroAMaIDTy9YbgBemNT-LN/view?usp=sharing

Please inform me if you require any additional information. I appreciate your ongoing assistance.

**Comment by fcyu** [comment]
To let TMT-Integrator generate the site report, you need to have `min site probability >= 0` (Yeah, it also took me a while to figure out.) You can set it to 0 (not filter out any sites) or 0.75 (filter out low confidence sites).

Since you have set 57.02146 as the variable modification on C, should you change the other C's variable modification to 57.04146+528.2859?

The PTMProphet command doesn't have some default flags, `KEEPOLD STATIC EM=1`, but have some new ones, `MODPREC=0 MAXTHREADS=0 NOSTACK`. I am not sure if you changed them on purpose or by mistake but you should remove `MAXTHREADS=0` because FragPipe runs multiple PTMProphet instances in parallel, and each instance uses 1 thread. PTMProphet has a bug that running in multiple-thread might generate corrupted mod.pep.xml files. For `NOSTACK`, you can keep it. I am not sure about the `MODPREC=0`. I suggest you use our default flags plus your modifications.

Best,

Fengchao

**Comment by lfu46** [comment]
Dear Fengchao,

I extend my sincere appreciation for your prompt response and valuable suggestion. Thanks to your guidance, TMT Integrator now successfully generates site reports.

Regarding the PTMProphet parameter, I made adjustments to certain flags. Initially, I encountered issues with PTMProphet for PTM localization and sought assistance from its developers. Unfortunately, they were unfamiliar with the MSFragger version and recommended using the Trans-Proteomic Pipeline (TPP) version, which ultimately resolved my problem. I replicated the command line from their software to MSFragger, confirming its efficacy, and maintained those settings.

Your counsel to remove `MAXTHREADS = 0` was duly noted. Upon reviewing the search log, I observed that `MAXTHREADS = 0` automatically switched to `MAXTHREADS = 1`, even though I initially set it as 0 in the command line. Consequently, I agree that setting it to 1 is the more prudent choice.

Regarding `NOSTACK`, I think that this parameter is suitable for my experiment, particularly in preventing the localization of C(528.2859) and C(57.02146) to the same site. In the case of `MODPREC = 0`, representing mass mod precision, I believe its significance is relatively negligible in this context.

Your suggestion to retain default flags for compatibility resonates with me, understanding the critical importance of ensuring seamless integration for a successful search.

I'd appreciate some clarification on the modification of variable C. Are you suggesting the addition of another variable modification of `C(528.2859 + 57.02146)`, representing `C(585.30736)`? I apologize for any confusion. Theoretically, these two modifications cannot coexist on C simultaneously, which is why I included NOSTACK in the PTMprophet parameters.

Additionally, I noticed that the TMT report file lacks a column specifying the type of modification quantified. In cases where multiple modifications exist on the same amino acid, such as `C(528.2859)` and `C(57.02146)`, I'm unsure how to discern the specific modification being quantified. Could you provide guidance on this matter? Alternatively, is it advisable to run the quantification process twice for each modification?

I would greatly appreciate any insights or suggestions you can provide on this matter. Thank you immensely for your continuous support.

Best regards,
Longping

![log MAXTHREADS = 1](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/55979d62-319d-4972-9b04-a5d8d4bdc672)
![tpp ptmprophet](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/f6921567-d2ff-4f64-be8c-c6d7475932f0)

**Comment by fcyu** [comment]
> Additionally, I noticed that the TMT report file lacks a column specifying the type of modification quantified. In cases where multiple modifications exist on the same amino acid, such as C(528.2859) and C(57.02146), I'm unsure how to discern the specific modification being quantified. Could you provide guidance on this matter? Alternatively, is it advisable to run the quantification process twice for each modification?

I don't think TMT-I support this feature.

Best,

Fengchao

**Comment by lfu46** [comment]
Thank you for providing explanation. Your continued support is sincerely valued and greatly appreciated.

Best regards,
Longping

**Comment by anesvi** [comment]
If you have different mods you need to run TMT-I twice to get seats two different site reports

**Comment by lfu46** [comment]
I appreciate your suggestion. It is really helpful.
