### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by carajj** [Nesvilab/TMT-Integrator#34]
Hi, when i run the TMT-Integrator to integrate results of TMT-11, i can not get result report and the error as follow:
**java -jar -Xmx16g /home/F/zjj/CPTAC_PAAD/MS/TMTIntegrator_v4.0.1.jar tmt-i_param_v4.0.1.yml /home/F/zjj/CPTAC/MS/psm/*_psm.tsv**
TMT-Integrator v4.0
Warning: No gene report is generated because all gene symbols in /home/F/zjj/CPTAC_PAAD/MS/psm/01CPTAC_PDA_W_JHU_20191125_LUMOS_f01_psm.tsv are missing. The protein ID will be used as gene in other reports.
UpdateColumns--- 0.61553 min.
**Error at: /home/F/zjj/CPTAC/MS/psm/01CPTAC_PDA_W_JHU_20191125_LUMOS_f02_psm.tsv java.lang.NullPointerException**

tmt-i_param_v4.0.1.yml was changed:
  **path: /home/F/zjj/CPTAC/MS/TMTIntegrator_v4.0.1.jar                 
  memory: 30                                    
  protein_database: /home/F/zjj/CPTAC/MS/2024-01-04-decoys-01output_fastq.fasta.fas            
  output: /home/F/zjj/CPTAC/MS/psm                       
  channel_num: 11                               
  ref_tag: 126**                                  

the dir of psm:
![image](https://github.com/Nesvilab/TMT-Integrator/assets/134495005/d58bcc73-21eb-4ac5-baa6-79c3bb8e28ee)

the annotation of TMT-11 like this: 
[annotation.txt](https://github.com/Nesvilab/TMT-Integrator/files/13884015/annotation.txt)
example
the each psm.tsv like this: 
[1.txt](https://github.com/Nesvilab/TMT-Integrator/files/13884017/1.txt)

this is the script of MSFragger:

		philosopher workspace --init

		MSFragger-3.8/MSFragger-3.8.jar ${params} ${s}.mzML
		philosopher peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy rev_ --database ${fa} --nonparam ${s}.pepXML

		philosopher proteinprophet interact-${s}.pep.xml
		philosopher database --annotate ${fa} --prefix rev_
		philosopher filter --sequential --razor --picked --tag rev_ --pepxml interact-${s}.pep.xml --protxml interact.prot.xml
		philosopher freequant --dir ${out}/${s}
		philosopher labelquant --brand tmt --plex 11 --dir ${out}/${s}
		philosopher report
		philosopher workspace --clean --nocheck

**Comment by haowBio** [comment]
I meet the same error, have you solved it ?

**Comment by fcyu** [comment]
Please use the latest FragPipe. 

Best,

Fengchao
