### ISSUE TITLE
Please Help: TMT integrator output doesn't have raw filename / experiment name in abundance columns

### ISSUE THREAD

**Issue by kwebber3** [Nesvilab/TMT-Integrator#35]
I am trying to optimize the MS for my experiment, so I am running about 50 files with 10 different types of mass spectrometery settings, all with the same TMT layout, so I want to use a single annotation.txt file, but I want to see which raw file each intensity came from. I don't have a reference channel, I am fine just using raw intensities. Do you have any suggestions about how to do this without making a separate folder and / or annotation file for each run? Is there a way to have both the channel name and the name of the file it came from? in example: "run1.raw sample-1". I definitely feel like this should be a feature.

**Comment by kwebber3** [comment]
![image](https://github.com/Nesvilab/TMT-Integrator/assets/26573132/e7f45bd8-2e55-4b66-8a51-2b7db41816f0)
Here is a snippet of some of the column names

**Comment by hsiaoyi0504** [comment]
There could be multiple files for the same TMT experiment, so seems like making your own annotation files with similar names might be easier.
