### ISSUE TITLE
Issue with TMT-Integrator in Fragpipe v22.0

### ISSUE THREAD

**Issue by lfu46** [Nesvilab/TMT-Integrator#36]
Hi developer team,

I encountered an issue after updating Fragpipe to version 22.0. When using TMT-Integrator to summarize my TMT-6 plex results, I set all twelve of my mzML files as the same experiment group.
![TMT-I_2](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/04f3330d-8918-4398-8ef6-dfff5d47c695)

However, the TMT report TSV file generated appears incorrect. The grouping seems to be malfunctioning, as the annotations from TM1 to Ctrl6 are repeated twelve times in the TSV file.
![TMT-I_1](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/e23aaa96-a549-4bd1-a4c5-84a6f8add724)
![TMT-I_4](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/30515b77-6791-4d97-8ec7-b699f0e17586)

This problem did not occur before the update. Additionally, after the update, the annotation file is sometimes not read properly by TMT-Integrator, requiring me to set the annotation file path manually for each file.
![TMT-I_3](https://github.com/Nesvilab/TMT-Integrator/assets/153141940/cf1553cc-314a-4ab9-9f71-46aaa87222be)

Could you please let me know how to resolve this issue? Thank you very much for your help.

Best,
Longping

**Comment by fcyu** [comment]
> However, the TMT report TSV file generated appears incorrect. The grouping seems to be malfunctioning, as the annotations from TM1 to Ctrl6 are repeated twelve times in the TSV file.

It is the intended behavior because you set 12 different bioreplicates.

Best,

Fengchao

**Comment by lfu46** [comment]
Hi Fengchao,

Thank you for your reply. I appreciate your help.

Best,
Longping
________________________________
