### ISSUE TITLE
Question Regarding Quantification Method in TMT-Integrator

### ISSUE THREAD

**Issue by lfu46** [Nesvilab/TMT-Integrator#37]
Hi TMT-Integrator Support Team,

I have a question about the quantification method used in TMT-Integrator. I have attached figures showing the quantification of a glycopeptide from my glycoproteomics experiment, where the peptide contains a localized glycomodification at a specific site. Additionally, I have included the settings I used for TMT-Integrator.

In the attached figure:

- The first line (highlighted in yellow) shows the quantification result provided by TMT-Integrator.
- The second line (highlighted in orange) shows the quantification result from another software.
- The third line (highlighted in red) presents the quantification result from the PSM table directly generated by IonQuant.

The peptide is quantified twice in the MSFragger results. Interestingly, the raw intensities from the Sequest and MSFragger results are identical. However, after processing with TMT-Integrator, the intensity of each channel (Tuni_1 to Ctrl_6) is significantly higher than the raw intensities from the PSM table—about ten times larger when comparing TMT-Integrator results with the PSM table data.

Could you please clarify the exact principles behind the summarization in TMT-Integrator? Are there any normalization factors applied to the raw results from the PSM table? I would greatly appreciate it if you could help explain the differences between the TMT-Integrator results and the PSM table data.

Thank you very much for your assistance.

Best regards,
Longping
![TMT-I issue 2](https://github.com/user-attachments/assets/f36a5e5c-1336-4306-9be6-86ac8194d28f)
![TMT-I issue](https://github.com/user-attachments/assets/6cbde95b-d7be-4da2-9e9f-51c46eced83d)
![TMT-I issue 3](https://github.com/user-attachments/assets/57798f0c-b08b-4534-81e7-6665cddb63ff)

**Comment by fcyu** [comment]
>  Interestingly, the raw intensities from the Sequest and MSFragger results are identical.

The raw intensities are directly read from the reporter ions in the MS2 without any modification, so they are supposed to be identical.

> However, after processing with TMT-Integrator, the intensity of each channel (Tuni_1 to Ctrl_6) is significantly higher than the raw intensities from the PSM table—about ten times larger when comparing TMT-Integrator results with the PSM table data.

> Could you please clarify the exact principles behind the summarization in TMT-Integrator? Are there any normalization factors applied to the raw results from the PSM table? I would greatly appreciate it if you could help explain the differences between the TMT-Integrator results and the PSM table data.

TMT-Integrator performs several steps of normalizations, which makes the intensity not comparable to the raw intensity (just like the intensities from any other software, different softwares are not comparable). We are preparing the manuscript, and hopefully it will be published soon.

Best,

Fengchao

**Comment by lfu46** [comment]
Thank you for your explanation. I appreciate your help.

Best,
Longping

**Comment by anesvi** [comment]
TNT-Integrator has been described and used in many papers, e.g. see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7331093/.
