### ISSUE TITLE
TMT10plex experimental design

### ISSUE THREAD

**Issue by stuomiva** [Nesvilab/TMT-Integrator#4]
Hi NesviLab (and other proteomics enthusiasts),

Thanks for your efforts in software development.  Earlier, FragPipe workflow has performed really great with my label free data analysis!

Now, I'm trying to analyze TMT10plex data using the newest FragPipe incarnation (v13.0) but I'm not sure how to properly do it.

Here's my experimental design (see also attached pdf):

-I'm monitoring the proximity-biotinylated proteins as a function of cell differentiation, where the labelings are performed at day 0 (undifferentiated) as well as days 1, 2 and 3 after induction of the differentiation.
-From each day, two samples are created, one with APEX2 labeling, and one control where a crucial ingredient is omitted.  The biotinylated materials are pulled-down with NeutrAvidin agarose and on-bead digested.
-Thus, there are eight unique samples from proximity-labeling experiment.
-Mixtures of all of the eight samples are prepared as references to normalize replicates.
-A full replicate of this scheme above is performed.
-The samples and references are TMT10plex-labeled in a random fashion within replicate.

In retrospect, I did the label randomization a bit too zealously, and now the two reference (or normalization) channels are both different among the replicate batches.  I think I should have fixed the reference channels first the same in both replicates and randomized just the pure samples...

[TMT10plex experimental design 1.pdf](https://github.com/Nesvilab/TMT-Integrator/files/4816099/TMT10plex.experimental.design.1.pdf)

Thus, there are at least these outstanding questions:
(1) How to set the FragPipe correctly, e.g., the "Experiment" and "Replicate" settings under the Workflow tab, as well as the labeling annotation table under Quant (labeling) tab to account for the idiosyncrasies of this particular experimental design?  

(2) I see that the optimal way to control the non-specific binding of proteins to the agarose beads is to subtract protein-wise the control channel intensities from the corresponding labeled sample channel intensities.  If any TMT channel normalization is done prior to subtraction, this would distort the relative protein intensity ratios and could easily lead to both false positives as well as false negatives.  Would the GN normalization (which is an option in the TMT labeling in FragPipe) take this into account...

Cheers and thanks again,

**Comment by sarah-haynes** [comment]
We have guidelines for assigning ‘Experiment’ and ‘Replicate’ for fractionated TMT experiments like yours [here](https://msfragger.nesvilab.org/tutorial_fragpipe.html#tmtitraq-data). Then in the ‘Quant (Labeling)’ tab, see [these instructions](https://msfragger.nesvilab.org/tutorial_fragpipe.html#isobaric-labeling-based-quantification) on how to annotate each channel. You can define the ‘pool’ channel separately for each multiplexed sample/‘Experiment’, so your design should be fine.

For your second question, TMT intensities are first log2 transformed and reference channel (or virtual reference if there isn't a pool channel) intensities are subtracted. Then outliers in each channel are removed using an interquartile range (IQR) algorithm. Users can choose whether to perform normalization in the output reports (e.g., median centering or global normalization; none means no normalization). So, normalization is done after reference channel subtraction, hopefully that answers your question.

Thanks for your interest in our tools!
Best,
Sarah

**Comment by stuomiva** [comment]
Hi Sarah,
Thanks for your help.  I'll follow the instructions and let you know if i have any trouble.
Cheers,
Sami
________________________________
